name: Continuous Integration

on:
  workflow_dispatch:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:

  test:

    name: Rust ${{ matrix.rust.version }}

    runs-on: ubuntu-latest

    outputs:
      passed_rustfmt: ${{ steps.rustfmt.outputs.passed_rustfmt }}
      passed_clippy: ${{ steps.clippy.outputs.passed_clippy }}

    strategy:
      fail-fast: false
      matrix:
        rust:
          - version: 1.56.1
            features:
          - version: stable
            features:

    steps:

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust.version }}
          components: rustfmt, clippy

      - id: rustfmt
        name: Rust format
        if: ${{ matrix.rust.version == 'stable' }}
        run: |
          cargo fmt --verbose --all -- --check
          echo "passed_rustfmt=${{ matrix.rust.version }}" >> "$GITHUB_OUTPUT"

      - id: clippy
        name: Clippy
        if: ${{ matrix.rust.version == '1.56.1' }}
        run: |
          cargo clippy --all ${{ matrix.rust.features }} --all-targets -- -D warnings
          echo "passed_clippy=${{ matrix.rust.version }}" >> "$GITHUB_OUTPUT"

      - id: test
        name: Compile and run tests
        run: cargo test ${{ matrix.rust.features }} --verbose

  code-checks:

    name: Code checks

    runs-on: ubuntu-latest

    needs: test

    steps:

      - name: Rustfmt
        run: |
          echo "Rustfmt run on ${{ needs.test.outputs.passed_rustfmt }}" >> "$GITHUB_STEP_SUMMARY"
          test "${{ needs.test.outputs.passed_rustfmt }}" = "stable"

      - name: Clippy
        run: |
          echo "Clippy run on ${{ needs.test.outputs.passed_clippy }}" >> "$GITHUB_STEP_SUMMARY"
          test "${{ needs.test.outputs.passed_clippy }}" = "1.56.1"

